Add support for posting CUFS certificate to straight to /symbol
wulkanowy/fake-log pull request #41
Opened 2022-01-14 22:52 UTC by drobotk

2022-01-23 19:31 UTC, mklkj requested changes

2022-01-23 19:31 UTC, mklkj commented on src/routes/uonetplus.js
> +router.post("/powiatwulkanowy(/)?", (req, res) => {
Nie będzie lepiej połączyć tego route'a z tym ze 132 linii (można używać all() dla POSTa i GETa jednocześnie)?

2022-01-24 19:26 UTC, drobotk commented on src/routes/uonetplus.js
> +router.post("/powiatwulkanowy(/)?", (req, res) => {
Hm, racja!

2022-01-24 19:29 UTC, Mateusz543 approved these changes

2022-02-12 11:28 UTC, mklkj approved these changes

2022-02-12 11:29 UTC, merged